### ISSUE TITLE
GETGLOB and GETGLOBVAR are mixed up

### ISSUE THREAD

**Issue by Shvandre** [tact-lang/ton-opcode#22]
In opcodes.yaml it is clearly seen, that GETGLOBVAR  does not have instruction-encoded argument, while GETGLOB does. 
```yaml
  # A.11.5. Global variable primitives.
  GETGLOBVAR:
  GETGLOB: ["int"]
```
Same goes for the ton docs.

However in opcodes.ts there is such handling of GETGLOBVAR
```ts
CP0Auto.insertHex('f841', 11, (slice) => {
    let i = slice.loadUint(5);
    return { code: `GETGLOBVAR`, args: [i] };
});
```

And as decompiler output I get
```fif
1 GETGLOBVAR
```

Also, when executing this code in @ton/sandbox I can clearly see that GETGLOB is being executed, not GETGLOBVAR.

Besides, I still do not understand which encoding is correct, and we probably need to fix this in docs too.
